"""empty message

Revision ID: 0aff54903f18
Revises: 90bd5b29dc16
Create Date: 2023-06-13 17:02:51.838489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aff54903f18'
down_revision = '90bd5b29dc16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_subcategories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('service_subcategory')
    op.drop_table('service_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_category',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('service_category_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='service_category_pkey'),
    sa.UniqueConstraint('name', name='service_category_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('service_subcategory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_category.id'], name='service_subcategory_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_subcategory_pkey'),
    sa.UniqueConstraint('name', name='service_subcategory_name_key')
    )
    op.drop_table('service_subcategories')
    op.drop_table('service_categories')
    # ### end Alembic commands ###
