"""empty message

Revision ID: 7559b29ccf85
Revises: 0aff54903f18
Create Date: 2023-06-15 17:46:55.300231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7559b29ccf85'
down_revision = '0aff54903f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'service_categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'service_subcategories', ['subcategory_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subcategory_id')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
