"""empty message

Revision ID: dbc2b3caf349
Revises: 9f68c52e9628
Create Date: 2023-06-07 18:23:45.374449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc2b3caf349'
down_revision = '9f68c52e9628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('condition', sa.String(length=120), nullable=False))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('name')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('condition')
        batch_op.drop_column('category')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
